# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import medications_pb2 as medications__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in medications_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MedicationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSchedule = channel.unary_unary(
                '/medication.MedicationService/CreateSchedule',
                request_serializer=medications__pb2.CreateScheduleRequest.SerializeToString,
                response_deserializer=medications__pb2.CreateScheduleResponse.FromString,
                _registered_method=True)
        self.GetAllSchedules = channel.unary_unary(
                '/medication.MedicationService/GetAllSchedules',
                request_serializer=medications__pb2.GetAllSchedulesRequest.SerializeToString,
                response_deserializer=medications__pb2.GetAllSchedulesResponse.FromString,
                _registered_method=True)
        self.GetUserSchedule = channel.unary_unary(
                '/medication.MedicationService/GetUserSchedule',
                request_serializer=medications__pb2.GetUserScheduleRequest.SerializeToString,
                response_deserializer=medications__pb2.MedicationSchedule.FromString,
                _registered_method=True)
        self.GetUserNextTakings = channel.unary_unary(
                '/medication.MedicationService/GetUserNextTakings',
                request_serializer=medications__pb2.GetUserNextTakingsRequest.SerializeToString,
                response_deserializer=medications__pb2.GetUserNextTakingsResponse.FromString,
                _registered_method=True)


class MedicationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllSchedules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserSchedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserNextTakings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MedicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSchedule,
                    request_deserializer=medications__pb2.CreateScheduleRequest.FromString,
                    response_serializer=medications__pb2.CreateScheduleResponse.SerializeToString,
            ),
            'GetAllSchedules': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllSchedules,
                    request_deserializer=medications__pb2.GetAllSchedulesRequest.FromString,
                    response_serializer=medications__pb2.GetAllSchedulesResponse.SerializeToString,
            ),
            'GetUserSchedule': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserSchedule,
                    request_deserializer=medications__pb2.GetUserScheduleRequest.FromString,
                    response_serializer=medications__pb2.MedicationSchedule.SerializeToString,
            ),
            'GetUserNextTakings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserNextTakings,
                    request_deserializer=medications__pb2.GetUserNextTakingsRequest.FromString,
                    response_serializer=medications__pb2.GetUserNextTakingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'medication.MedicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('medication.MedicationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MedicationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medication.MedicationService/CreateSchedule',
            medications__pb2.CreateScheduleRequest.SerializeToString,
            medications__pb2.CreateScheduleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllSchedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medication.MedicationService/GetAllSchedules',
            medications__pb2.GetAllSchedulesRequest.SerializeToString,
            medications__pb2.GetAllSchedulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserSchedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medication.MedicationService/GetUserSchedule',
            medications__pb2.GetUserScheduleRequest.SerializeToString,
            medications__pb2.MedicationSchedule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserNextTakings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/medication.MedicationService/GetUserNextTakings',
            medications__pb2.GetUserNextTakingsRequest.SerializeToString,
            medications__pb2.GetUserNextTakingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
